version: '3'

services:
  client:
    build: ./frontend
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:3000
    volumes:
      - ./frontend:/frontend
    command: yarn start

