version: '3'

services:
  client:
    build: ./frontend
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend/src:/usr/cr-app/frontend/src
      - ./frontend/public:/cr-app/frontend/public
    command: yarn start

